---
- name: Building server certificate and private Key
  local_action:
    module: ansible.builtin.shell
    cmd: "{{ build_serverCert_cmd }}"
  run_once: True

- name: Signing server certificate
  local_action:
    module: ansible.builtin.shell
    cmd: "{{ sign_serverCert_cmd }}"
  run_once: True