---  
- name: "Configuring firewalld {{ RW_Listener_port }} port"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ firewalld_maxscale_ports }}"
  notify: reload firewalld