---
all:
  children:
    vbox:
      children:
        lbservers:
          children:
            haproxy:
              hosts:
                haproxy-01:
                  ansible_host: 10.100.0.91
                haproxy-02:
                  ansible_host: 10.100.0.92
        webservers:
          children:
            apache:
              hosts:
                httpd-01:
                  ansible_host: 10.100.0.11
                httpd-02:
                  ansible_host: 10.100.0.12
            nginx:
              hosts:
                nginx-01:
                  ansible_host: 10.100.0.21
                nginx-02:
                  ansible_host: 10.100.0.22
              vars:
                ansible_python_interpreter: /usr/bin/python3
        mariadb:
          hosts:
            mariadb_01:
              ansible_host: 10.100.0.81
            mariadb_02:
              ansible_host: 10.100.0.82
            mariadb_03:
              ansible_host: 10.100.0.83
        infra:
          hosts:
            puppetmaster:
              ansible_host: 10.100.0.51
            gitlab:
              ansible_host: 10.100.0.52
            dns:
              ansible_host: 10.100.0.53
            openvpn:
              ansible_host: 10.100.0.54
            opnsense:
              ansible_host: 10.100.0.55