---
- name : Cleaning 127.0.1.1 record within each {{ host_file }} pacemaker nodes 
  ansible.builtin.lineinfile:
    path: "{{ hosts_file }}"
    regexp: "127.0.1.1"
    state: absent

- name : Appending each pacemaker nodes in {{ host_file }}
  ansible.builtin.blockinfile:
    path: "{{ hosts_file }}"
    block: |
      {{ item.ip }} {{ item.hostname }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.hostname }}"
  loop: "{{ pacemaker_hosts }}"