---
- name : Appending each pacemaker nodes in {{ host_file }}
  ansible.builtin.blockinfile:
    path: "{{ hosts_file }}"
    block: |
      {{ item.ip }} {{ item.hostname }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.hostname }}"
  loop: "{{ pacemaker_hosts }}"