- name: Update HAproxy configuration safely
  ansible.builtin.template:
    src: "{{ HAproxy_template_file }}"
    dest: "{{ HAproxy_config_file }}"
    owner: "{{ HAproxy_config_file_owner }}"
    group: "{{ HAproxy_config_file_group }}"
    mode: "{{ HAproxy_config_file_mode }}"
    validate: "{{ HAproxy_validate }}"
    backup: "{{ HAproxy_backup }}"
  notify: reload HAproxy