---
# tasks file for Haproxy
- include_vars: vars/haproxy.yml

- name : installing and configuring HAproxy 
  include_tasks: common.yml
  
- name : configuring HAproxy pacemaker resources
  include_tasks: resources_cfg.yml
  when: ansible_hostname == HAproxy_main_node

- name : configuring HAproxy pacemaker resource constraints
  include_tasks: constraints_cfg.yml
  when: ansible_hostname == HAproxy_main_node

- name : Enabling HAproxy firewalld services 
  include_tasks: firewalld.yml

- name : Configuring HAproxy 
  include_tasks: haproxy_config.yml