---
- name : "Setting MariaDB SST SSL support parameters at {{ galera_enc_file }}"
  ansible.builtin.blockinfile:
    create: yes
    path: "{{ galera_enc_file }}"
    owner: "{{ galera_conf_file_owner }}"
    group: "{{ galera_conf_file_group }}"
    mode: "{{ galera_conf_file_mode }}"
    marker: "# {mark} : Mysqld section (SST SSL) - ANSIBLE_MANAGED_BLOCK"
    insertafter: "# END : Mysqld section (TDE encryption) - ANSIBLE_MANAGED_BLOCK"
    state: present
    block: |
      {{ lookup ('template', sst_section_ssl_template )}}