---
# vars file for galera
OS_family: "{{ ansible_facts['os_family'] }}"
OS_distro: "{{ ansible_facts['distribution'] }}"
OS_release: "{{ ansible_facts['distribution_release'] }}"

role_dir: "{{ playbook_dir + '/roles/maxscale' }}"

main_task_dir: "{{ role_dir + '/tasks' }}"
main_vars_dir: "{{ role_dir + '/vars' }}"
main_template_dir: "{{ role_dir + '/templates' }}"

OS_template_dir: "{{ main_template_dir + '/' + OS_family + '/' + OS_release }}"
OS_task_dir: "{{ main_task_dir + '/' + OS_family + '/' + OS_release }}"
OS_vars_dir: "{{ main_vars_dir + '/' + OS_family + '/' + OS_release }}"

# Modify variables here and only
# Remember to modify vault.yml to have custom maxscale user credentials per environment

# Template : maxscale.j2
galera_hosts:
    - { hostname: mariadb-01, ip: 10.100.0.81 }
    - { hostname: mariadb-02, ip: 10.100.0.82 }
    - { hostname: mariadb-03, ip: 10.100.0.83 }