---
# vars file for galera
OS_family: "{{ ansible_facts['os_family'] }}"
OS_distro: "{{ ansible_facts['distribution'] }}"
OS_release: "{{ ansible_facts['distribution_release'] }}"

role_dir: "{{ playbook_dir + '/roles/maxscale' }}"

main_task_dir: "{{ role_dir + '/tasks' }}"
main_vars_dir: "{{ role_dir + '/vars' }}"
main_template_dir: "{{ role_dir + '/templates' }}"

OS_template_dir: "{{ main_template_dir + '/' + OS_family + '/' + OS_release }}"
OS_task_dir: "{{ main_task_dir + '/' + OS_family + '/' + OS_release }}"
OS_vars_dir: "{{ main_vars_dir + '/' + OS_family + '/' + OS_release }}"

# Modify variables here and only
maxscale_hosts:
  - { hostname: maxscale-01, ip: 10.100.0.31 }
  - { hostname: maxscale-02, ip: 10.100.0.32 }

CA_CN: "vagrant-ca-maxscale"
CA_key: "ca-key-maxscale.pem"
CA_cert: "ca-maxscale-crt.pem"
CA_config: "ca-maxscale.conf"

server_CN: "vagrant-maxscale"
serverKey: "key-maxscale.pem"
serverReq: "req-maxscale.pem"
serverCert: "crt-maxscale.pem"
server_config: "maxscale.conf"