- name: Enable service maxscale
  ansible.builtin.service:
    name: maxscale
    enabled: yes
    
- name: Start service maxscale, if not started
  ansible.builtin.service:
    name: maxscale
    state: started

- name : "Setting up Maxscale configuration file"
  ansible.builtin.template:
    src: "{{ maxscale_configuration_template }}"
    dest: "{{ maxscale_configuration_template_dest }}"
    owner: "{{ maxscale_configuration_owner }}"
    group: "{{ maxscale_configuration_group }}"
    mode: "{{ maxscale_configuration_mode }}"
  notify: restart maxscale