---
# tasks file for base
  #Debian
- name: common configuration for Debian servers
  block:
    #Loading Debian variables
    - name : Loading Debian common variables
      include_vars: "{{ Debian_vars_dir + '/common-vars.yml' }}"

    - name : Loading Debian security variables
      include_vars: "{{ Debian_vars_dir + '/security-vars.yml' }}"

      #Tasks for Debian
    - name : installing and configuring Debian common packages
      include_tasks: "{{ Debian_task_dir + '/common/main.yml' }}"

    - name : configuring security parameters for Debian
      include_tasks: "{{ Debian_task_dir + '/security/main.yml' }}"

    - name : Flush handlers 
      meta: flush_handlers
      
  when: OS_family == "Debian"

  #RHEL
- name: common configuration for RHEL servers
  block:  
    #Loading RHEL variables
    - name : Loading RHEL common variables
      include_vars: "{{ RHEL_vars_dir + '/common-vars.yml' }}"

    - name : Loading RHEL security variables
      include_vars: "{{ RHEL_vars_dir + '/security-vars.yml' }}"

      #Tasks for RHEL
    - name : installing and configuring DRHEL common packages
      include_tasks: "{{ RHEL_task_dir + '/common/main.yml' }}"

    - name : configuring security parameters for RHEL
      include_tasks: "{{ RHEL_task_dir + '/security/main.yml' }}"

    - name : Flush handlers 
      meta: flush_handlers

  when: OS_family == "RedHat"
