---
# tasks file for base
  #Debian
- name: common configuration for Debian servers
  block:
    #Loading Debian variables
    - name : Loading Debian common variables
      include_vars: "{{ vars_dir + '/common-vars.yml' }}"

    - name : Loading Debian SELinux variables
      include_vars: "{{ vars_dir + '/security-vars.yml' }}"

    #Tasks for Debian
    - name : installing and configuring Debian common packages
      include_tasks: "{{ task_dir + '/common/main.yml' }}"

    - name : configuring security parameters for Debian
      include_tasks: "{{ task_dir + '/security/main.yml' }}"

    - name : Flush handlers 
      meta: flush_handlers
      
  when: OS_family == "Debian"

  #RHEL
- name: common configuration for RHEL servers
  block:
    - name : installing RHEL common packages
      include_tasks: "{{ OS_family + '-common.yml' }}"

    - name : installing selinux packages for RHEL
      include_tasks: "{{ OS_family + '-selinux.yml' }}"
  when: OS_family == "RedHat"
