---
# vars file for pacemaker
OS_family: "{{ ansible_facts['os_family'] }}"
OS_distro: "{{ ansible_facts['distribution'] }}"
OS_release: "{{ ansible_facts['distribution_release'] }}"

role_dir: "{{ playbook_dir + '/roles/pacemaker' }}"

main_task_dir: "{{ role_dir + '/tasks' }}"
main_vars_dir: "{{ role_dir + '/vars' }}"
main_template_dir: "{{ role_dir + '/templates' }}"

OS_template_dir: "{{ main_template_dir + '/' + OS_family + '/' + OS_release }}"
OS_task_dir: "{{ main_task_dir + '/' + OS_family + '/' + OS_release }}"
OS_vars_dir: "{{ main_vars_dir + '/' + OS_family + '/' + OS_release }}"

hosts_file: /etc/hosts
# Packages/dependencies
pcmk_packages:
  - pacemaker
  - pcs
  - psmisc
pcmk_packages_version: latest

#firewalld configuration
firewalld_HA_service: high-availability
firewalld_HA_enabled: yes #permanent
firewalld_HA_state: enabled