---
- name: Authenticating all nodes
  ansible.builtin.command: 
    cmd: "{{ pcsd_auth_cmd }} {{ pcmk_hosts_str }} -u {{ hacluster_user }} -p {{ hacluster_passwd }}"

- name: Initializing cluster
  ansible.builtin.command:
    cmd: "{{ pcsd_setup_cmd }} {{ pcmk_cluster_name }} {{ pcmk_hosts_str }}"

- name: Starting cluster
  ansible.builtin.command:
    cmd: "{{ pcsd_start_cmd }}"

- name: Disabling stonith
  ansible.builtin.command:
    cmd: "{{ pcsd_stonith_disable_cmd }}"