---
- name : Enabling pcsd daemon and initializing hacluster user 
  include_tasks: common.yml
  
- name : Cleaning native cluster configurations
  include_tasks: clean.yml

- name : FACTS - Retrieving pacemaker hosts
  include_tasks: get_pcmk_hosts.yml

- name : Initiliazing cluster configuation
  with_items: "{{ pacemaker_hosts }}"
  include_tasks: init.yml
  when: item.main_node