---
- name : Installing MariaDB release signing key
  ansible.builtin.apt_key:
    url: "{{ mariadb_release_signing_key }}"
    state: "{{ mariadb_release_signing_key_state }}"

- name : Adding MariaDB repo
  ansible.builtin.apt_repository:
    repo: "{{ mariadb_repository }}"
    state: "{{ mariadb_repository_state }}"

- name : "Installing Maxscale package : {{ maxscale_packages }}"
  ansible.builtin.apt:
    name: "{{ maxscale_packages }}"
    state: "{{ maxscale_packages_state }}"
    update_cache: yes