---
# tasks for common subtasks
- name: Configuring records in {{ host_file }}
  include_tasks: config_hosts.yml

- name: Installing MariaDB dependencies and Maxscale packages
  include_tasks: config_dependencies.yml