---  
- name: "Configuring firewalld mysql service"
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ galera_firewalld_service_config }}"

- name: "Configuring firewalld galera port"
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ galera_firewalld_port_config }}"
  notify: reload firewalld