#[mariadb]
#State Snapshots Transfers
wsrep_sst_method: "mariabackup"
wsrep_sst_auth: "{{ mariabackup_sst_user }}:{{ mariabackup_sst_pwd }}"
wsrep_cluster_name: gdp_galera_cluster
wsrep_sst_donor: "{{ mariadb_hosts|map(attribute=\"hostname\")|reject('search', ansible_facts['hostname'])|join(',') }},"
wsrep_node_name: "{{ ansible_facts['hostname']}}"
  ## wsrep_sst_auth credentials
mariabackup_sst_user: mariabackup

#SSL communications (defaults)
ssl_cert: "{{ ssl_certificate }}"
ssl_key: "{{ ssl_privateKey }}"
ssl_ca: "{{ ssl_cacert }}"
wsrep_provider_options: "socket.ssl_cert={{ ssl_cert }};socket.ssl_key={{ ssl_key }};socket.ssl_ca={{ ssl_ca }}"

#Logging
log_output: "FILE"
log_basename: mariadb
log_root: "/var/log/mysql"
log_error: "{{ log_root + '/mariadb.err' }}"
slow_query_log_file: "{{ log_root + '/mariadb-slow.log' }}"
sst_log_archive: "1"
sst_log_archive_dir: "{{ log_root + '/mariadb-sst.log' }}"


