---
- name : "Deploying initial Galera Cluster configuration file at {{ galera_conf_file }}"
  ansible.builtin.template:
    src: "{{ galera_conf_file_template }}"
    dest: "{{ galera_conf_file }}"
    owner: "{{ galera_conf_file_owner }}"
    group: "{{ galera_conf_file_group }}"
    mode: "{{ galera_conf_file_mode }}"