---
# tasks for configfile_section subtasks
- name: "Initializing MariaDB Galera configuration file"
  include_tasks: "mariadb_galera.yml"

- name: "Initializing MariaDB server configuration file"
  include_tasks: "mariadb_server.yml"
