---
# This file gathers required defaults resources for an active/active Maxscale cluster
# --> Debian/buster/aa-maxscale/defaults-vars.yml

# Resource stickiness
- name : Configuring defaults resource stickiness after failover
  ansible.builtin.command:
    cmd: "{{ pcsd_resource_defaults_cmd }}
    resource-stickiness={{ resource_stickiness }}"