hosts_file: /etc/hosts

# Template : mariadb_repo_setup.j2
mariadb_repo_setup_template: "{{ OS_template_dir + '/common/mariadb_repo_setup.j2' }}"
mariadb_repo_setup_template_dest: /tmp/mariadb_repo_setup
mariadb_repo_setup_owner: root
mariadb_repo_setup_group: root
mariadb_repo_setup_mode: '0755'

# Tasks : 
  ## Common : config_dependencies.yml
mariadb_server_version: mariadb-10.5
mariadb_server_version_real: mariadb-10.5
mariadb_maxscale_version: 2.5