host_file: /etc/hosts
maxscale_conf_root: /etc/maxscale.d
#Dependencies
mariadb_dependencies_packages_state: latest
mariadb_dependencies_packages:
  - software-properties-common
  - dirmngr
  - socat

#Repository
mariadb_release_signing_key: https://mariadb.org/mariadb_release_signing_key.asc
mariadb_release_signing_key_state: present
mariadb_repository: deb [arch=amd64,arm64,ppc64el] https://ftp.igh.cnrs.fr/pub/mariadb/repo/10.5/debian buster main
mariadb_repository_state: present

#Packages for galera
maxscale_packages:
  - maxscale
maxscale_packages_state: latest