# OpenSSL configurations
  ## SSL communications
    ### CA configuration
CA_emailAddress: "anguyen.ext@dataone.fr"
CA_organization: "Groupe Diffusion Plus"
CA_organizationUnit: "Direction des Systèmes d'Informations"
CA_location: "Saint-Aubin-sur-Gaillon"
CA_state: "Eure" 
CA_country: "FR"
      #### OpenSSL options
        ##### CA
          ###### Key
CA_key_type: "genrsa"
CA_key_size: "2048"
          ###### Cert
CA_cert_exp: "365000"
    ### Server certificate configuration
server_emailAddress: "anguyen.ext@dataone.fr"
server_organization: "Groupe Diffusion Plus"
server_organizationUnit: "Direction des Systèmes d'Informations"
server_location: "Saint-Aubin-sur-Gaillon"
server_state: "Eure" 
server_country: "FR"
      #### OpenSSL options
        ##### Key
serverKey_size: "rsa:2048" #and type
serverCert_exp: "365000"
        ##### Cert
serverCert_serial: "01"

# Certificates
  ## SSL communication
    ### CA
CA_config_template: "ca.conf.j2"
    ### Server
server_config_template: "server.conf.j2"

# Certificates/Keys location
files_dir: "/home/alx/repo/ansible-gdp/playbooks/vagrant/HA-LAMP/roles/galera/files"

  ### SSL communication
    #### Template
CAconf_template: "{{ OS_template_dir + '/encryption/ssl/' + CA_config_template }}"
serverconf_template: "{{ OS_template_dir + '/encryption/ssl/' + server_config_template }}"
local_CAconf_storage: "{{ files_dir + '/' + CA_config }}"
local_serverConfig_storage: "{{ files_dir + '/' + server_config }}"
req_configs:
  - { template_file: "{{ CAconf_template }}", conf_file: "{{ local_CAconf_storage }}" }
  - { template_file: "{{ serverconf_template }}", conf_file: "{{ local_serverConfig_storage }}" }
    #### Local
      ##### CA
local_CAkey_storage: "{{ files_dir + '/' + CA_key }}"
local_CAcert_storage: "{{ files_dir + '/' + CA_cert }}"
      ##### Server
local_serverReq_storage: "{{ files_dir + '/' + serverReq }}"
local_serverKey_storage: "{{ files_dir + '/' + serverKey }}"
local_serverCert_storage: "{{ files_dir + '/' + serverCert }}"
    #### Remote
ssl_certificate: "{{ encryption_keys_dir + '/' + serverCert }}"
ssl_privateKey: "{{ encryption_keys_dir + '/' + serverKey }}"
ssl_cacert: "{{ encryption_keys_dir + '/' + CA_cert }}"
SSL_certificates:
  - { source_file: "{{ local_CAcert_storage }}", dest_file: "{{ ssl_cacert }}" }
  - { source_file: "{{ local_serverKey_storage }}", dest_file: "{{ ssl_privateKey }}" }
  - { source_file: "{{ local_serverCert_storage }}", dest_file: "{{ ssl_certificate }}" }

# OpenSSL commands
  ## SSL Communications
    ### CA
build_CAkey_cmd: "openssl {{ CA_key_type }} {{ CA_key_size }} > {{ local_CAkey_storage }}"
build_CAcert_cmd:  "openssl req -new \
-x509 -nodes -days {{ CA_cert_exp }} \
-key {{ local_CAkey_storage }} \
-out {{ local_CAcert_storage }} \
-config {{ local_CAconf_storage }}"
    ### Server
build_serverCert_cmd: "openssl req -newkey {{ serverKey_size }} \
-days {{ serverCert_exp }} \
-nodes \
-keyout {{ local_serverKey_storage }} \
-out {{ local_serverReq_storage }} \
-config {{ local_serverConfig_storage }}"
sign_serverCert_cmd: "openssl x509 -req \
-in {{ local_serverReq_storage }} \
-days {{ serverCert_exp }} \
-CA {{ local_CAcert_storage }} \
-CAkey {{ local_CAkey_storage }} \
-set_serial {{ serverCert_serial }} \
-out {{ local_serverCert_storage }}"
