---
# handlers file for bind9
- name : reload firewalld
  ansible.builtin.service: 
    name: firewalld 
    state: reloaded

- name : restart named
  ansible.builtin.service: 
    name: named
    state: restarted